Feature - Disable Frontend...
xiaohutai/jsonapi pull request #78
Opened 2018-03-30 20:38 UTC by Raistlfiren

Added the ability to disable the frontend through a configuration value and just show a blank page.

2018-03-31 08:50 UTC, GwendolenLynch requested changes

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +        }
Can you un-nest this. Early returns are far better for human reading of logical intent, and there is rarely a time where an if statement inside another is valid.

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +                ['disableFrontend', -1025]
This is massively high (late in terms of priority, but not the point :stuck_out_tongue: ). Does it really need to be?

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +        //$response = $event->getResponse();
Remove commented code

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +        //Get route name
Comment serves no purpose :wink:

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +                    $event->stopPropagation();
Not needed. You're setting a non-null value below

2018-03-31 08:50 UTC, GawainLynch commented on src/JSONAPIExtension.php
> +                        }
You're better off throwing a `HttpException` here with a 403 or similar. This is just a nightmare to debug if for some reason it is being unexpectedly called … the Samuel L. Jackson Law of Assumption in full flight.

2018-04-01 03:10 UTC, Raistlfiren commented
@GawainLynch  - You have reminded me once again why I submit PRs and have you review them. Do you have any job openings? I would love for you to be my boss. ;) :)

Seriously though, thank you @GawainLynch for the review. I will revise my code as requested, and I hope to push some changes within the next few days.

2018-04-01 16:13 UTC, GawainLynch commented
No worries mate … Being you, I thought I'd go a bit harder than normal. :smiley_cat: 

Also, @xiaohutai is on leave, so someone has to harras people for no good reason :innocent:

2018-04-16 13:44 UTC, xiaohutai commented
Hi @Raistlfiren ,

~I'm wondering why would you want this?~ This feature disables the website, so that you only get the JSONAPI.

Also when doing:
```
$this->setDisableFrontend($config['disablefrontend']);
```
I think you need to add a `isset` check, so it wouldn't break when updating and that value is not present?

2018-04-18 20:09 UTC, Raistlfiren commented
@xiaohutai - I was wanting to add the feature because we are only using the Bolt instance for the API to feed child websites. We have no need for the frontend. It would be handy to be able to disable the frontend completely, and only include the backend and jsonapi routes.

I tested having no value in my config for `disableFrontend`, and the value actually returns NULL. 

Is the check necessary? I bet @GawainLynch has his own two cents. ;) lol

2018-04-20 13:46 UTC, xiaohutai commented
It's an array, it will give a notice if it's not there:

![jsonapi-notice](https://user-images.githubusercontent.com/4630335/39054449-f756e7a8-44b1-11e8-9234-d80d751f258a.png)


Maybe:
```
        $disablefrontend = isset($config['disablefrontend']) ? $config['disablefrontend'] : true;
        $this->setDisableFrontend($disablefrontend);
```
what do you think?

2018-04-20 14:19 UTC, Raistlfiren commented
I agree @xiaohutai, but I did set the default to false instead of true. Since currently the frontend is always displayed.

2018-04-20 15:13 UTC, merged